apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-tsb-config
  namespace: argocd
spec:
  destination:
    namespace: gitops
    server: https://corp-edge.aws.scratch.caas.tetrate.com:443
  project: default
  source:
    directory:
      include: "{tsb-config.yaml}"
    path: demos/observability/artifacts
    repoURL: https://github.com/tetratecx/tetrate-platform-ntt
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - AllowSharedResource=true
    - IgnoreInClusterResources=true
    - PruneLast=true    