apiVersion: tsb.tetrate.io/v2
kind: Tenant
metadata:
  name: "default"
  annotations:
    tsb.tetrate.io/organization: "tetrate"
spec:
  displayName: "Default"
  profiles:
    - organizations/tetrate/profiles/http-profile